name: Bicep-StorageAccount-PrivateEndpoint

trigger:
- main

variables:
  resourceGroupName: 'example'
  location: 'westeurope'
  azureSubscription: 'AzureConnection'
  resourcePrefix: 'bicep'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps: